# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  parcel:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          paths:
            - react/parcel/node_modules
          keys:
          - v1-parcel-dependencies-{{ checksum "react/parcel/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-parcel-dependencies-

      - run:
          name: Install
          command: cd react/parcel && npm install

      - save_cache:
          paths:
            - react/parcel/node_modules
          key: v1-parcel-dependencies-{{ checksum "react/parcel/package.json" }}

      # run tests!
      - run:
          name: Run all unit tests
          command: cd react/parcel && npm test

  webpack:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          paths:
            - react/webpack4/node_modules
          keys:
          - v1-w4-dependencies-{{ checksum "react/webpack4/package.json" }}
          - v1-w4-dependencies-

      - run:
          name: Install
          command: cd react/webpack4 && npm install

      - run:
          name: Check vulnerabilities
          command: npm audit

      - save_cache:
          paths:
            - react/webpack4/node_modules
          key: v1-w4-dependencies-{{ checksum "react/webpack4/package.json" }}

      - run:
          name: Run  tests
          command: cd react/webpack4 && npm test

workflows:
  version: 2
  test_starters:
    jobs:
      - parcel
      - webpack
